name: Deploy Frontend Application

on:
  push:
    branches:
      - main
      - new-feature

env:
  DOCKER_IMAGE: xiaojieyi/234-deploylab-frontend  # 替换为您的Docker Hub用户名

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          build-args: |
            TARGET=ng-deploy

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp docker-compose.yml deploy/
          echo "DOCKER_HUB_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}" > deploy/.env

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/frontend
            cd /home/ubuntu/frontend
            docker logout  # 清除可能存在的错误凭据
            echo "$DOCKER_HUB_TOKEN" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose down || true
            docker compose up -d --pull always

  deploy-new-feature:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/new-feature'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:new-feature
          build-args: |
            TARGET=ng-deploy

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp docker-compose-prod.yml deploy/docker-compose.yml
          echo "DOCKER_HUB_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}" > deploy/.env

      - name: Deploy to staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "/home/ubuntu/frontend-new"

      - name: Start staging container
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/frontend-new
            source .env
            docker logout
            echo "$DOCKER_HUB_TOKEN" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose down || true
            docker compose up -d --pull always