name: Deploy frontend application

on:
  push:
    branches:
      - main
      - new-feature

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      # [原有步骤保持不变...]
      - name: Deploy to Port 8086
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/frontend
            cat <<< "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d

  deploy-new-feature:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/new-feature'
    steps:
      # [原有步骤保持不变...]
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: xiaojieyi/234-deploylab-frontend:new-feature

      - name: Deploy to Port 9999
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/frontend-new
            cat <<< "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker compose -f docker-compose-prod.yml down
            docker compose -f docker-compose-prod.yml pull
            docker compose -f docker-compose-prod.yml up -d